# SmartTour.Jo Netlify Configuration
# Static React Application - No server required

[build]
  # React build command  
  command = "cd frontend && npm install && npm run build"
  
  # Static files output directory
  publish = "frontend/build"
  
  # Repository base directory
  base = "."

# Build environment
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  CI = "false"

# Single Page Application redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    
# Static asset caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions (if needed later)
[functions]
  directory = "netlify/functions"