# DigitalOcean App Platform Configuration
# SmartTour.Jo Deployment Settings

name: smarttour-jo
services:
- name: frontend
  source_dir: /frontend
  github:
    repo: KaramQ6/demo
    branch: main
  run_command: npm start
  build_command: npm install --legacy-peer-deps && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: GENERATE_SOURCEMAP
    value: "false"
  - key: CI
    value: "false"
  - key: DISABLE_ESLINT_PLUGIN
    value: "true"

static_sites:
- name: smarttour-static
  source_dir: /frontend
  github:
    repo: KaramQ6/demo
    branch: main
  build_command: npm ci --production=false && npm run build
  output_dir: /build
  index_document: index.html
  error_document: index.html
  catchall_document: index.html
  envs:
  - key: NODE_ENV
    value: production
  - key: GENERATE_SOURCEMAP
    value: "false"
