# DigitalOcean App Platform Configuration
# SmartTour.Jo Deployment Settings

name: smarttour-jo

static_sites:
- name: smarttour-frontend
  source_dir: /frontend
  github:
    repo: KaramQ6/demo
    branch: main
  build_command: npm ci --legacy-peer-deps && npm run build
  output_dir: /build
  index_document: index.html
  error_document: index.html
  catchall_document: index.html
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: GENERATE_SOURCEMAP
    value: "false"
  - key: CI
    value: "false"
  - key: DISABLE_ESLINT_PLUGIN
    value: "true"
